package a5project;

import java.io.*;
import java.sql.*;
import java.util.*;

/**
 * MIS-307-A5 project for building a small Inventory Management Program to handle retail tasks at a Hobby Shop.
 * @authors ajensen, dtan, dazobler
 */

public class a5project {
	
	public static Scanner in = new Scanner(System.in);
	
	public static void main (String[] args) throws IOException, ClassNotFoundException, SQLException, Exception
	{
		//Step 1: Connect to Database	
		//Make sure that path is set correctly for DB connection
		if (args.length == 0) {   
           System.out.println( "Usage: java -classpath driver_class_path" 
                 + File.pathSeparator 
                 + ". BigSexy propertiesFile");
           return;
        }
        
		//Set up connection to DB from database properties
        SimpleDataSource.init(args[0]);
        
        //Connect to DB
        /*
        Connection conn = SimpleDataSource.getConnection();
        Statement stat = conn.createStatement();
        
        stat.execute("DROP TABLE Employees");
        stat.execute("DROP TABLE Inventory");
        stat.execute("DROP TABLE Supplier");
        stat.execute("DROP TABLE Orderline");
        stat.execute("DROP TABLE Customers");

        stat.execute("CREATE TABLE Employees (EmployeeID INT GENERATED BY DEFAULT AS IDENTITY, EmployeeName VARCHAR(40), EmployeeType CHAR(1))");
        stat.execute("CREATE TABLE Inventory (ProductID INT GENERATED BY DEFAULT AS IDENTITY, ProductName VARCHAR(50), Quantity SMALLINT, Price DEC(10,2), SupplierID SMALLINT)");
        stat.execute("CREATE TABLE Supplier (SupplierID INT GENERATED BY DEFAULT AS IDENTITY, SupplierName VARCHAR(20))");
        stat.execute("CREATE TABLE Orderline (TransactionID INT GENERATED BY DEFAULT AS IDENTITY, TransactionDate DATE, CustomerID SMALLINT, ProductID SMALLINT, Price DEC(10,2), Quantity SMALLINT, TotalPrice DEC(10,2))");
        stat.execute("CREATE TABLE Customers (CustomerID INT GENERATED BY DEFAULT AS IDENTITY, CustomerName VARCHAR(30) NOT NULL, Loyalty CHAR(1), Sales SMALLINT) ");
              
        stat.execute("INSERT INTO Employees VALUES (333666, 'Austin Jensen', 'M')");
        stat.execute("INSERT INTO Employees VALUES (127660, 'Dominic Tan', 'M')");
        stat.execute("INSERT INTO Employees VALUES (127659, 'Derek Zobler', 'C')");
                
        stat.execute("INSERT INTO Supplier VALUES (DEFAULT, 'USAGundamStore.com')");
        stat.execute("INSERT INTO Supplier VALUES (DEFAULT, 'SideShowToy.com')");
        stat.execute("INSERT INTO Supplier VALUES (DEFAULT, 'HobbyLink Japan Ltd')");
                
        stat.execute("INSERT INTO Inventory VALUES (DEFAULT, 'Star Wars 1/12 Scale Model Kit - Boba Fett Bandai', 4, 24.99, 1)");
        stat.execute("INSERT INTO Inventory VALUES (DEFAULT, 'Ant-Man Sixth Scale Figure by Hot Toys', 1, 243.00, 2)");
        stat.execute("INSERT INTO Inventory VALUES (DEFAULT, '1/100 Master Grade MS-06F Zaku II Ver.2.0', 2 , 27.59, 3)");
                               
        stat.execute("INSERT INTO Customers VALUES (DEFAULT, 'Young Woong Park', 'Y', 4)");
        stat.execute("INSERT INTO Customers VALUES (DEFAULT, 'Ian Cornish', 'N', 2)");
        stat.execute("INSERT INTO Customers VALUES (DEFAULT, 'Luping Wang', 'Y', 1)");
        */  
		//Step 2: Run the main menu
        boolean run = true;
        boolean clearance = false;
        while (run) 
        {
        	System.out.print("Please log-in as either an C)lerk or a M)anager (Enter 'Q' at any time to quit): "); //Insert Q option to quit at any level?
        	String cmd = in.nextLine();
        
        	//Exits the program
        	if (cmd.equalsIgnoreCase("Q"))
        	{
        		run = false;
        		Login.logOut(run);
        	}
        
        	//Runs the Clerk menu after logging in
        	else if (cmd.equalsIgnoreCase("C"))
        	{
        		System.out.printf("\nEnter Clerk ID: ");
        		String m = in.nextLine();
        		int n = Integer.parseInt(m);
        		if (Login.logIC(n, clearance)) {
        			Employees.Clerk();
        		}
        	}
        
        	//Runs the Manager menu after logging in
        	else if (cmd.equalsIgnoreCase("M"))
        	{
        		System.out.printf("\nEnter Manager ID: ");
        		String m = in.nextLine();
        		int n = Integer.parseInt(m);
        		if (Login.logIM(n, clearance)) {
        			Employees.Manager();
        			//manager methods start here
        		}
        	}    	
        }
        //Close out everything as program terminates
        //Close scanner?
        in.close();
        //stat.close();
	}
}


        

